/**
 * Data-driven onboarding step definitions — the ordered list of questions. Parent-focused *content*
 * lives here; the engine (packages/domain) and screens (mobile) stay generic. Reorder/add a question
 * by editing this array. One primary question per screen; sensitive steps carry reassurance copy.
 */
import type { OnboardingStepDef } from '@challenge42/types';

export const ONBOARDING_STEPS: readonly OnboardingStepDef[] = [
  // ---- A. Basics ----------------------------------------------------------------------------
  {
    id: 'firstName',
    section: 'basics',
    kind: 'text',
    key: 'firstName',
    title: 'First, what should we call you?',
    subtitle: 'We’ll use your first name to keep things personal.',
    placeholder: 'First name',
    required: true,
  },
  {
    id: 'age',
    section: 'basics',
    kind: 'number',
    key: 'age',
    title: 'How old are you?',
    subtitle: 'Used only to estimate your nutrition — never shown to anyone.',
    min: 16,
    max: 100,
    required: true,
  },
  {
    id: 'sex',
    section: 'basics',
    kind: 'single_select',
    key: 'sex',
    title: 'Which should we use for nutrition estimates?',
    subtitle: 'This changes the validated calorie formula. Optional — pick what fits.',
    options: [
      { value: 'female', label: 'Female' },
      { value: 'male', label: 'Male' },
      { value: 'unspecified', label: 'Prefer not to say' },
    ],
    required: true,
  },
  {
    id: 'height',
    section: 'basics',
    kind: 'height',
    key: 'heightCm',
    title: 'How tall are you?',
    required: true,
  },
  {
    id: 'currentWeight',
    section: 'basics',
    kind: 'weight',
    key: 'currentWeightKg',
    title: 'And your current weight?',
    subtitle: 'Private by default. This is just your starting point.',
    required: true,
  },
  {
    id: 'goalWeight',
    section: 'basics',
    kind: 'weight',
    key: 'goalWeightKg',
    title: 'Do you have a long-term goal weight?',
    subtitle: 'Optional. This is a long-term aim — not a 42-day target.',
    required: false,
  },
  {
    id: 'city',
    section: 'basics',
    kind: 'text',
    key: 'city',
    title: 'What city are you in?',
    subtitle: 'For your time zone and the challenge map. We never store your address.',
    placeholder: 'City',
    required: false,
  },
  {
    id: 'state',
    section: 'basics',
    kind: 'text',
    key: 'state',
    title: 'And your state or region?',
    placeholder: 'State / region',
    required: false,
  },

  // ---- B. Parent / household ----------------------------------------------------------------
  {
    id: 'isParent',
    section: 'household',
    kind: 'boolean',
    key: 'isParent',
    title: 'Are you a parent or caregiver?',
    subtitle: 'This challenge is built around real family life.',
    required: true,
  },
  {
    id: 'childrenCount',
    section: 'household',
    kind: 'number',
    key: 'childrenCount',
    title: 'How many children are in your household?',
    min: 0,
    max: 15,
    required: true,
    condition: (a) => a.isParent === true,
  },
  {
    id: 'childAgeBands',
    section: 'household',
    kind: 'multi_select',
    key: 'childAgeBands',
    title: 'What are their ages?',
    subtitle: 'Select all that apply.',
    options: [
      { value: 'baby_under_1', label: 'Baby under 1', emoji: '👶' },
      { value: 'age_1_2', label: '1–2' },
      { value: 'age_3_5', label: '3–5' },
      { value: 'age_6_9', label: '6–9' },
      { value: 'age_10_13', label: '10–13' },
      { value: 'teen', label: 'Teen' },
      { value: 'adult_children', label: 'Adult children' },
      { value: 'other', label: 'Other' },
    ],
    minSelect: 1,
    required: true,
    condition: (a) => a.isParent === true,
  },
  {
    id: 'parentSeason',
    section: 'household',
    kind: 'single_select',
    key: 'parentSeason',
    title: 'How would you describe your current season?',
    options: [
      { value: 'new_baby', label: 'New baby', emoji: '🍼' },
      { value: 'toddler_chaos', label: 'Toddler chaos', emoji: '🌪️' },
      { value: 'preschool', label: 'Preschool years' },
      { value: 'school_age', label: 'School-age kids' },
      { value: 'multiple_ages', label: 'Multiple age groups' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    condition: (a) => a.isParent === true,
  },
  {
    id: 'cookForCount',
    section: 'household',
    kind: 'single_select',
    key: 'cookForCount',
    title: 'How many people do you normally cook dinner for?',
    options: [
      { value: '1', label: 'Just me' },
      { value: '2', label: '2' },
      { value: '3_4', label: '3–4' },
      { value: '5_plus', label: '5+' },
    ],
    required: true,
  },
  {
    id: 'mealResponsibility',
    section: 'household',
    kind: 'single_select',
    key: 'mealResponsibility',
    title: 'Who usually handles meals?',
    options: [
      { value: 'mostly_me', label: 'Mostly me' },
      { value: 'mostly_partner', label: 'Mostly my partner' },
      { value: 'shared', label: 'We share it' },
      { value: 'varies', label: 'Changes day to day' },
      { value: 'someone_else', label: 'Someone else' },
    ],
    required: true,
  },
  {
    id: 'eatingBarriers',
    section: 'household',
    kind: 'multi_select',
    key: 'eatingBarriers',
    title: 'What usually makes healthy eating hard?',
    subtitle: 'Pick the real ones — no judgment.',
    options: [
      { value: 'no_time', label: 'No time' },
      { value: 'picky_kids', label: 'Kids are picky' },
      { value: 'eating_out', label: 'Eating out' },
      { value: 'work_schedule', label: 'Work schedule' },
      { value: 'grocery_cost', label: 'Grocery cost' },
      { value: 'meal_planning', label: 'Meal planning' },
      { value: 'separate_meals', label: 'Cooking separate meals' },
      { value: 'stress', label: 'Stress' },
      { value: 'exhaustion', label: 'Exhaustion' },
      { value: 'weekends', label: 'Weekends' },
      { value: 'social_events', label: 'Social events' },
      { value: 'other', label: 'Other' },
    ],
    minSelect: 1,
    required: true,
  },

  // ---- C. Goal ------------------------------------------------------------------------------
  {
    id: 'primaryGoal',
    section: 'goal',
    kind: 'single_select',
    key: 'primaryGoal',
    title: 'What matters most over the next 42 days?',
    options: [
      { value: 'lose_weight', label: 'Lose weight' },
      { value: 'build_habits', label: 'Build healthier habits' },
      { value: 'feel_in_control', label: 'Feel more in control of food' },
      { value: 'get_back_to_exercise', label: 'Get back into exercise' },
      { value: 'improve_energy', label: 'Improve energy' },
      { value: 'build_consistency', label: 'Build consistency' },
    ],
    required: true,
  },
  {
    id: 'secondaryGoals',
    section: 'goal',
    kind: 'multi_select',
    key: 'secondaryGoals',
    title: 'Anything else you’re hoping for?',
    subtitle: 'Optional — select any that apply.',
    options: [
      { value: 'lose_weight', label: 'Lose weight' },
      { value: 'build_habits', label: 'Healthier habits' },
      { value: 'feel_in_control', label: 'Control around food' },
      { value: 'get_back_to_exercise', label: 'Back into exercise' },
      { value: 'improve_energy', label: 'More energy' },
      { value: 'build_consistency', label: 'Consistency' },
    ],
    required: false,
  },
  {
    id: 'motivation',
    section: 'goal',
    kind: 'longtext',
    key: 'motivation',
    title: 'Why does this matter to you right now?',
    subtitle: 'Optional, and private. We’ll save it and show it back to you when it’s hard.',
    placeholder: 'e.g. “I want more energy for my kids.”',
    required: false,
  },

  // ---- D. History / barriers ----------------------------------------------------------------
  {
    id: 'falloffTriggers',
    section: 'history',
    kind: 'multi_select',
    key: 'falloffTriggers',
    title: 'What usually causes you to fall off track?',
    options: [
      { value: 'weekends', label: 'Weekends' },
      { value: 'eating_out', label: 'Eating out' },
      { value: 'stress', label: 'Stress' },
      { value: 'poor_sleep', label: 'Poor sleep' },
      { value: 'work', label: 'Work' },
      { value: 'kids', label: 'Kids' },
      { value: 'travel', label: 'Travel' },
      { value: 'hunger', label: 'Hunger' },
      { value: 'motivation', label: 'Lack of motivation' },
      { value: 'all_or_nothing', label: 'All-or-nothing thinking' },
      { value: 'missing_one_day', label: 'Missing one day and giving up' },
      { value: 'other', label: 'Other' },
    ],
    minSelect: 1,
    required: true,
  },
  {
    id: 'priorAttempts',
    section: 'history',
    kind: 'single_select',
    key: 'priorAttempts',
    title: 'How many times have you seriously tried before?',
    subtitle: 'There’s no wrong answer — this helps us support you better.',
    options: [
      { value: 'first', label: 'This is my first real attempt' },
      { value: '1_2', label: '1–2' },
      { value: '3_5', label: '3–5' },
      { value: 'more_than_5', label: 'More than 5' },
      { value: 'lost_count', label: 'I’ve lost count' },
    ],
    required: true,
  },
  {
    id: 'falloffPattern',
    section: 'history',
    kind: 'single_select',
    key: 'falloffPattern',
    title: 'When you fall off track, what usually happens?',
    options: [
      { value: 'restart_next_day', label: 'I restart the next day' },
      { value: 'restart_monday', label: 'I restart Monday' },
      { value: 'give_up_days', label: 'I give up for several days' },
      { value: 'stop_completely', label: 'I stop completely' },
      { value: 'depends', label: 'It depends' },
    ],
    required: true,
  },

  // ---- E. Food preferences ------------------------------------------------------------------
  {
    id: 'dislikedFoods',
    section: 'food',
    kind: 'taglist',
    key: 'dislikedFoods',
    title: 'Any foods you really don’t want?',
    subtitle: 'Optional. Add a few — we’ll keep them out of your plan.',
    placeholder: 'e.g. mushrooms',
    required: false,
  },
  {
    id: 'allergies',
    section: 'food',
    kind: 'multi_select',
    key: 'allergies',
    title: 'Any allergies we should know about?',
    options: [
      { value: 'none', label: 'None' },
      { value: 'peanuts', label: 'Peanuts' },
      { value: 'tree_nuts', label: 'Tree nuts' },
      { value: 'dairy', label: 'Dairy' },
      { value: 'eggs', label: 'Eggs' },
      { value: 'gluten', label: 'Gluten' },
      { value: 'shellfish', label: 'Shellfish' },
      { value: 'soy', label: 'Soy' },
      { value: 'other', label: 'Other' },
    ],
    required: false,
  },
  {
    id: 'dietaryRestrictions',
    section: 'food',
    kind: 'multi_select',
    key: 'dietaryRestrictions',
    title: 'Do you follow any way of eating?',
    options: [
      { value: 'none', label: 'No restrictions' },
      { value: 'vegetarian', label: 'Vegetarian' },
      { value: 'vegan', label: 'Vegan' },
      { value: 'pescatarian', label: 'Pescatarian' },
      { value: 'gluten_free', label: 'Gluten-free' },
      { value: 'dairy_free', label: 'Dairy-free' },
      { value: 'halal', label: 'Halal' },
      { value: 'kosher', label: 'Kosher' },
      { value: 'other', label: 'Other' },
    ],
    required: false,
  },
  {
    id: 'favoriteCuisines',
    section: 'food',
    kind: 'multi_select',
    key: 'favoriteCuisines',
    title: 'What does your family love to eat?',
    options: [
      { value: 'american', label: 'American' },
      { value: 'mexican', label: 'Mexican' },
      { value: 'italian', label: 'Italian' },
      { value: 'mediterranean', label: 'Mediterranean' },
      { value: 'asian', label: 'Asian' },
      { value: 'indian', label: 'Indian' },
      { value: 'bbq', label: 'BBQ / grilling' },
      { value: 'comfort', label: 'Comfort food' },
    ],
    required: false,
  },
  {
    id: 'cookTimePref',
    section: 'food',
    kind: 'single_select',
    key: 'cookTimePref',
    title: 'How long do you realistically want dinner to take?',
    options: [
      { value: 'under_15', label: 'Under 15 minutes' },
      { value: '15_30', label: '15–30 minutes' },
      { value: '30_45', label: '30–45 minutes' },
      { value: 'enjoy_cooking', label: 'I actually enjoy cooking' },
    ],
    required: true,
  },
  {
    id: 'costImportance',
    section: 'food',
    kind: 'single_select',
    key: 'costImportance',
    title: 'How important is keeping food costs down?',
    options: [
      { value: 'very', label: 'Very important' },
      { value: 'somewhat', label: 'Somewhat important' },
      { value: 'flexible', label: 'Flexible' },
    ],
    required: true,
  },
  {
    id: 'eatOutFrequency',
    section: 'food',
    kind: 'single_select',
    key: 'eatOutFrequency',
    title: 'How often does your family eat out or order in?',
    options: [
      { value: 'rarely', label: 'Rarely' },
      { value: '1_2_weekly', label: '1–2 times a week' },
      { value: '3_4_weekly', label: '3–4 times a week' },
      { value: '5_plus_weekly', label: '5+ times a week' },
    ],
    required: true,
  },
  {
    id: 'sameMealForFamily',
    section: 'food',
    kind: 'boolean',
    key: 'sameMealForFamily',
    title: 'Want meals your whole family can eat?',
    subtitle: 'Most parents say yes — no cooking two dinners.',
    required: true,
  },
  {
    id: 'familyAdventurousness',
    section: 'food',
    kind: 'single_select',
    key: 'familyAdventurousness',
    title: 'How adventurous is your family with food?',
    options: [
      { value: 'very_picky', label: 'Very picky' },
      { value: 'somewhat_picky', label: 'Somewhat picky' },
      { value: 'flexible', label: 'Pretty flexible' },
      { value: 'very_adventurous', label: 'Very adventurous' },
      { value: 'na', label: 'Not applicable' },
    ],
    required: true,
  },

  // ---- F. Daily lifestyle -------------------------------------------------------------------
  {
    id: 'activityLevel',
    section: 'lifestyle',
    kind: 'single_select',
    key: 'activityLevel',
    title: 'How active are you these days?',
    options: [
      { value: 'sedentary', label: 'Mostly sedentary', hint: 'Little intentional activity' },
      { value: 'light', label: 'Some walking / light activity' },
      { value: 'moderate', label: 'Regularly active' },
      { value: 'very_active', label: 'Very active' },
    ],
    required: true,
  },
  {
    id: 'timeAvailable',
    section: 'lifestyle',
    kind: 'single_select',
    key: 'timeAvailable',
    title: 'Realistically, how much time most days for movement?',
    options: [
      { value: '10', label: '10 minutes' },
      { value: '20', label: '20 minutes' },
      { value: '30', label: '30 minutes' },
      { value: '45_plus', label: '45+ minutes' },
      { value: 'varies', label: 'It varies a lot' },
    ],
    required: true,
  },
  {
    id: 'enjoyedActivities',
    section: 'lifestyle',
    kind: 'multi_select',
    key: 'enjoyedActivities',
    title: 'Which activities do you actually enjoy?',
    options: [
      { value: 'walking', label: 'Walking' },
      { value: 'running', label: 'Running' },
      { value: 'strength', label: 'Strength training' },
      { value: 'home_workouts', label: 'Home workouts' },
      { value: 'gym', label: 'Gym' },
      { value: 'cycling', label: 'Cycling' },
      { value: 'sports', label: 'Sports' },
      { value: 'yoga', label: 'Yoga' },
      { value: 'hiking', label: 'Hiking' },
      { value: 'none_yet', label: 'None yet' },
    ],
    required: false,
  },
  {
    id: 'activityTimePref',
    section: 'lifestyle',
    kind: 'single_select',
    key: 'activityTimePref',
    title: 'When is exercise most realistic for you?',
    options: [
      { value: 'early_morning', label: 'Early morning' },
      { value: 'morning', label: 'Morning' },
      { value: 'lunch', label: 'Lunch' },
      { value: 'afternoon', label: 'Afternoon' },
      { value: 'evening', label: 'Evening' },
      { value: 'after_bedtime', label: 'After kids go to bed' },
      { value: 'varies', label: 'Changes daily' },
    ],
    required: true,
  },

  // ---- G. Schedule --------------------------------------------------------------------------
  {
    id: 'scheduleUnpredictability',
    section: 'schedule',
    kind: 'multi_select',
    key: 'scheduleUnpredictability',
    title: 'What makes your schedule hardest to predict?',
    subtitle: 'We’ll use this to help you adjust on tough days.',
    options: [
      { value: 'work', label: 'Work' },
      { value: 'kids', label: 'Kids' },
      { value: 'sleep', label: 'Sleep' },
      { value: 'sports', label: 'Sports / activities' },
      { value: 'childcare', label: 'Childcare' },
      { value: 'travel', label: 'Travel' },
      { value: 'shift_work', label: 'Shift work' },
      { value: 'predictable', label: 'My schedule is predictable' },
    ],
    minSelect: 1,
    required: true,
  },

  // ---- H. Health / safety -------------------------------------------------------------------
  {
    id: 'safetyIntro',
    section: 'safety',
    kind: 'info',
    title: 'A few private questions',
    subtitle:
      'These keep you safe. If any apply, we’ll adjust your plan and never push an aggressive target. Your answers are private.',
  },
  {
    id: 'isPregnant',
    section: 'safety',
    kind: 'boolean',
    key: 'isPregnant',
    title: 'Are you currently pregnant?',
    required: true,
    reassurance: 'If yes, we won’t generate a weight-loss target — we’ll focus on healthy habits.',
  },
  {
    id: 'isRecentPostpartum',
    section: 'safety',
    kind: 'boolean',
    key: 'isRecentPostpartum',
    title: 'Have you given birth recently?',
    required: true,
  },
  {
    id: 'isBreastfeeding',
    section: 'safety',
    kind: 'boolean',
    key: 'isBreastfeeding',
    title: 'Are you currently breastfeeding?',
    required: true,
  },
  {
    id: 'hasHealthConditions',
    section: 'safety',
    kind: 'boolean',
    key: 'hasHealthConditions',
    title: 'Any health conditions that affect nutrition, weight, or exercise?',
    required: true,
  },
  {
    id: 'underMedicalCare',
    section: 'safety',
    kind: 'boolean',
    key: 'underMedicalCare',
    title: 'Are you under a professional’s care for any of those?',
    required: true,
  },
  {
    id: 'eatingDisorderHistory',
    section: 'safety',
    kind: 'boolean',
    key: 'eatingDisorderHistory',
    title: 'Any history that makes calorie or weight tracking unsafe for you?',
    subtitle: 'Including disordered eating. We’ll adapt to keep this supportive, not triggering.',
    required: true,
    reassurance: 'If yes, we’ll skip numeric calorie targets and focus on gentle consistency.',
  },

  // ---- Baseline (pilot research) ------------------------------------------------------------
  {
    id: 'confidenceCompletion',
    section: 'baseline',
    kind: 'scale',
    key: 'confidenceCompletion',
    title: 'How confident are you that you’ll complete all 42 days?',
    min: 1,
    max: 10,
    required: true,
  },
  {
    id: 'habitSatisfaction',
    section: 'baseline',
    kind: 'scale',
    key: 'habitSatisfaction',
    title: 'How satisfied are you with your current health habits?',
    min: 1,
    max: 10,
    required: true,
  },
  {
    id: 'foodControl',
    section: 'baseline',
    kind: 'scale',
    key: 'foodControl',
    title: 'How in control do you feel around food right now?',
    min: 1,
    max: 10,
    required: true,
  },
  {
    id: 'exerciseConsistency',
    section: 'baseline',
    kind: 'scale',
    key: 'exerciseConsistency',
    title: 'How consistent have you been with exercise recently?',
    min: 1,
    max: 10,
    required: true,
  },
  {
    id: 'successDefinition',
    section: 'baseline',
    kind: 'longtext',
    key: 'successDefinition',
    title: 'What would make these 42 days a success for you?',
    subtitle: 'Optional. In your own words.',
    placeholder: 'e.g. “Stop starting over.”',
    required: false,
  },
];
