/**
 * Data-driven onboarding step definitions — the ordered list of questions. All question *content*
 * lives here; the engine (packages/domain) and screens (mobile) stay generic. Reorder/add a question
 * by editing this array. One primary question per screen; sensitive steps carry reassurance copy.
 *
 * Kept intentionally lean (~2 dozen steps): the essentials the Target Engine + safety routing +
 * core personalization need, without survey fatigue. Deeper preference capture returns later
 * (e.g. in-app, contextually) rather than all up front.
 */
import type { OnboardingStepDef } from '@challenge42/types';

export const ONBOARDING_STEPS: readonly OnboardingStepDef[] = [
  // ---- A. Basics ----------------------------------------------------------------------------
  {
    id: 'firstName',
    section: 'basics',
    kind: 'text',
    key: 'firstName',
    title: 'First, what should we call you?',
    subtitle: 'We’ll use your first name to keep things personal.',
    placeholder: 'First name',
    required: true,
  },
  {
    id: 'age',
    section: 'basics',
    kind: 'number',
    key: 'age',
    title: 'How old are you?',
    subtitle: 'Used only to estimate your nutrition — never shown to anyone.',
    min: 16,
    max: 100,
    required: true,
  },
  {
    id: 'sex',
    section: 'basics',
    kind: 'single_select',
    key: 'sex',
    title: 'Which should we use for nutrition estimates?',
    subtitle: 'This changes the validated calorie formula. Optional — pick what fits.',
    options: [
      { value: 'female', label: 'Female' },
      { value: 'male', label: 'Male' },
      { value: 'unspecified', label: 'Prefer not to say' },
    ],
    required: true,
  },
  {
    id: 'height',
    section: 'basics',
    kind: 'height',
    key: 'heightCm',
    title: 'How tall are you?',
    required: true,
  },
  {
    id: 'currentWeight',
    section: 'basics',
    kind: 'weight',
    key: 'currentWeightKg',
    title: 'And your current weight?',
    subtitle: 'Private by default. This is just your starting point.',
    required: true,
  },
  {
    id: 'goalWeight',
    section: 'basics',
    kind: 'weight',
    key: 'goalWeightKg',
    title: 'Do you have a long-term goal weight?',
    subtitle: 'Optional. This is a long-term aim — not a 42-day target.',
    required: false,
  },

  // ---- B. Household -------------------------------------------------------------------------
  {
    id: 'cookForCount',
    section: 'household',
    kind: 'single_select',
    key: 'cookForCount',
    title: 'How many people do you normally cook dinner for?',
    options: [
      { value: '1', label: 'Just me' },
      { value: '2', label: '2' },
      { value: '3_4', label: '3–4' },
      { value: '5_plus', label: '5+' },
    ],
    required: true,
  },
  {
    id: 'eatingBarriers',
    section: 'household',
    kind: 'multi_select',
    key: 'eatingBarriers',
    title: 'What usually makes healthy eating hard?',
    subtitle: 'Pick the real ones — no judgment.',
    options: [
      { value: 'no_time', label: 'No time' },
      { value: 'eating_out', label: 'Eating out' },
      { value: 'work_schedule', label: 'Work schedule' },
      { value: 'grocery_cost', label: 'Grocery cost' },
      { value: 'meal_planning', label: 'Meal planning' },
      { value: 'separate_meals', label: 'Cooking separate meals' },
      { value: 'stress', label: 'Stress' },
      { value: 'exhaustion', label: 'Exhaustion' },
      { value: 'weekends', label: 'Weekends' },
      { value: 'social_events', label: 'Social events' },
      { value: 'other', label: 'Other' },
    ],
    minSelect: 1,
    required: true,
  },

  // ---- C. Goal ------------------------------------------------------------------------------
  {
    id: 'primaryGoal',
    section: 'goal',
    kind: 'single_select',
    key: 'primaryGoal',
    title: 'What matters most over the next 42 days?',
    options: [
      { value: 'lose_weight', label: 'Lose weight' },
      { value: 'build_habits', label: 'Build healthier habits' },
      { value: 'feel_in_control', label: 'Feel more in control of food' },
      { value: 'get_back_to_exercise', label: 'Get back into exercise' },
      { value: 'improve_energy', label: 'Improve energy' },
      { value: 'build_consistency', label: 'Build consistency' },
    ],
    required: true,
  },
  {
    id: 'motivation',
    section: 'goal',
    kind: 'longtext',
    key: 'motivation',
    title: 'Why does this matter to you right now?',
    subtitle: 'Optional, and private. We’ll save it and show it back to you when it’s hard.',
    placeholder: 'e.g. “I want more energy day to day.”',
    required: false,
  },

  // ---- D. History / barriers ----------------------------------------------------------------
  {
    id: 'falloffTriggers',
    section: 'history',
    kind: 'multi_select',
    key: 'falloffTriggers',
    title: 'What usually causes you to fall off track?',
    options: [
      { value: 'weekends', label: 'Weekends' },
      { value: 'eating_out', label: 'Eating out' },
      { value: 'stress', label: 'Stress' },
      { value: 'poor_sleep', label: 'Poor sleep' },
      { value: 'work', label: 'Work' },
      { value: 'travel', label: 'Travel' },
      { value: 'hunger', label: 'Hunger' },
      { value: 'motivation', label: 'Lack of motivation' },
      { value: 'all_or_nothing', label: 'All-or-nothing thinking' },
      { value: 'missing_one_day', label: 'Missing one day and giving up' },
      { value: 'other', label: 'Other' },
    ],
    minSelect: 1,
    required: true,
  },

  // ---- E. Food preferences ------------------------------------------------------------------
  {
    id: 'allergies',
    section: 'food',
    kind: 'multi_select',
    key: 'allergies',
    title: 'Any allergies we should know about?',
    options: [
      { value: 'none', label: 'None' },
      { value: 'peanuts', label: 'Peanuts' },
      { value: 'tree_nuts', label: 'Tree nuts' },
      { value: 'dairy', label: 'Dairy' },
      { value: 'eggs', label: 'Eggs' },
      { value: 'gluten', label: 'Gluten' },
      { value: 'shellfish', label: 'Shellfish' },
      { value: 'soy', label: 'Soy' },
      { value: 'other', label: 'Other' },
    ],
    required: false,
  },
  {
    id: 'cookTimePref',
    section: 'food',
    kind: 'single_select',
    key: 'cookTimePref',
    title: 'How long do you realistically want dinner to take?',
    options: [
      { value: 'under_15', label: 'Under 15 minutes' },
      { value: '15_30', label: '15–30 minutes' },
      { value: '30_45', label: '30–45 minutes' },
      { value: 'enjoy_cooking', label: 'I actually enjoy cooking' },
    ],
    required: true,
  },
  {
    id: 'costImportance',
    section: 'food',
    kind: 'single_select',
    key: 'costImportance',
    title: 'How important is keeping food costs down?',
    options: [
      { value: 'very', label: 'Very important' },
      { value: 'somewhat', label: 'Somewhat important' },
      { value: 'flexible', label: 'Flexible' },
    ],
    required: true,
  },

  // ---- F. Daily lifestyle -------------------------------------------------------------------
  {
    id: 'activityLevel',
    section: 'lifestyle',
    kind: 'single_select',
    key: 'activityLevel',
    title: 'How active are you these days?',
    options: [
      { value: 'sedentary', label: 'Mostly sedentary', hint: 'Little intentional activity' },
      { value: 'light', label: 'Some walking / light activity' },
      { value: 'moderate', label: 'Regularly active' },
      { value: 'very_active', label: 'Very active' },
    ],
    required: true,
  },

  // ---- H. Health / safety -------------------------------------------------------------------
  {
    id: 'isPregnant',
    section: 'safety',
    kind: 'boolean',
    key: 'isPregnant',
    title: 'Are you currently pregnant?',
    subtitle: 'A few private questions that keep you safe. Your answers stay private.',
    required: true,
    reassurance: 'If yes, we won’t generate a weight-loss target — we’ll focus on healthy habits.',
  },
  {
    id: 'isRecentPostpartum',
    section: 'safety',
    kind: 'boolean',
    key: 'isRecentPostpartum',
    title: 'Have you given birth recently?',
    required: true,
  },
  {
    id: 'isBreastfeeding',
    section: 'safety',
    kind: 'boolean',
    key: 'isBreastfeeding',
    title: 'Are you currently breastfeeding?',
    required: true,
  },
  {
    id: 'hasHealthConditions',
    section: 'safety',
    kind: 'boolean',
    key: 'hasHealthConditions',
    title: 'Any health conditions that affect nutrition, weight, or exercise?',
    required: true,
  },
  {
    id: 'underMedicalCare',
    section: 'safety',
    kind: 'boolean',
    key: 'underMedicalCare',
    title: 'Are you under a professional’s care for any of those?',
    required: true,
  },
  {
    id: 'eatingDisorderHistory',
    section: 'safety',
    kind: 'boolean',
    key: 'eatingDisorderHistory',
    title: 'Any history that makes calorie or weight tracking unsafe for you?',
    subtitle: 'Including disordered eating. We’ll adapt to keep this supportive, not triggering.',
    required: true,
    reassurance: 'If yes, we’ll skip numeric calorie targets and focus on gentle consistency.',
  },

  // ---- Baseline (pilot research) ------------------------------------------------------------
  {
    id: 'confidenceCompletion',
    section: 'baseline',
    kind: 'scale',
    key: 'confidenceCompletion',
    title: 'How confident are you that you’ll complete all 42 days?',
    min: 1,
    max: 10,
    required: true,
  },
  {
    id: 'habitSatisfaction',
    section: 'baseline',
    kind: 'scale',
    key: 'habitSatisfaction',
    title: 'How satisfied are you with your current health habits?',
    min: 1,
    max: 10,
    required: true,
  },
];
