/**
 * Regenerate apps/mobile/src/features/live/usMapData.ts — accurate continental-US state borders
 * (Albers-USA, AK/HI insets) plus per-state centroids (STATE_XY) projected through the SAME
 * projection, so a real challenger's location dot lands on their state.
 *
 * Usage (from repo root):
 *   npm i --no-save d3-geo topojson-client
 *   node scripts/genUsMap.mjs
 *
 * Source data: us-atlas states-10m (US Census cartographic boundaries, public domain).
 */
import { writeFileSync } from 'node:fs';
import * as topojson from 'topojson-client';
import { geoAlbersUsa, geoPath, geoCentroid } from 'd3-geo';

const TOPO_URL = 'https://cdn.jsdelivr.net/npm/us-atlas@3/states-10m.json';
const W = 960;
const H = 600;

// Full state name → USPS 2-letter code (matches the code stored on the profile).
const NAME_TO_ABBR = {
  Alabama: 'AL',
  Alaska: 'AK',
  Arizona: 'AZ',
  Arkansas: 'AR',
  California: 'CA',
  Colorado: 'CO',
  Connecticut: 'CT',
  Delaware: 'DE',
  'District of Columbia': 'DC',
  Florida: 'FL',
  Georgia: 'GA',
  Hawaii: 'HI',
  Idaho: 'ID',
  Illinois: 'IL',
  Indiana: 'IN',
  Iowa: 'IA',
  Kansas: 'KS',
  Kentucky: 'KY',
  Louisiana: 'LA',
  Maine: 'ME',
  Maryland: 'MD',
  Massachusetts: 'MA',
  Michigan: 'MI',
  Minnesota: 'MN',
  Mississippi: 'MS',
  Missouri: 'MO',
  Montana: 'MT',
  Nebraska: 'NE',
  Nevada: 'NV',
  'New Hampshire': 'NH',
  'New Jersey': 'NJ',
  'New Mexico': 'NM',
  'New York': 'NY',
  'North Carolina': 'NC',
  'North Dakota': 'ND',
  Ohio: 'OH',
  Oklahoma: 'OK',
  Oregon: 'OR',
  Pennsylvania: 'PA',
  'Rhode Island': 'RI',
  'South Carolina': 'SC',
  'South Dakota': 'SD',
  Tennessee: 'TN',
  Texas: 'TX',
  Utah: 'UT',
  Vermont: 'VT',
  Virginia: 'VA',
  Washington: 'WA',
  'West Virginia': 'WV',
  Wisconsin: 'WI',
  Wyoming: 'WY',
};

const topo = await fetch(TOPO_URL).then((r) => r.json());
const states = topojson.feature(topo, topo.objects.states);

const proj = geoAlbersUsa().fitSize([W, H], states);
const path = geoPath(proj);
const roundPath = (d) => (d ? d.replace(/-?\d+\.?\d*/g, (n) => Math.round(parseFloat(n))) : '');
const statePaths = states.features.map((f) => roundPath(path(f))).filter(Boolean);

// Per-state centroid, projected and normalized to 0–1, keyed by USPS code.
const stateXY = {};
for (const f of states.features) {
  const abbr = NAME_TO_ABBR[f.properties.name];
  if (!abbr) continue;
  const p = proj(geoCentroid(f));
  if (p)
    stateXY[abbr] = {
      x: Math.round((p[0] / W) * 1e4) / 1e4,
      y: Math.round((p[1] / H) * 1e4) / 1e4,
    };
}

const out =
  `// AUTO-GENERATED by scripts/genUsMap.mjs (d3-geo geoAlbersUsa over us-atlas states-10m). Do not edit.\n` +
  `// Accurate continental-US state borders (AK/HI as insets), projected to a ${W}×${H} viewBox.\n` +
  `export const US_VIEWBOX = '0 0 ${W} ${H}';\n` +
  `export const US_STATE_PATHS: readonly string[] = ${JSON.stringify(statePaths)};\n` +
  `// State centroid (0–1 of the viewBox) keyed by USPS code — where a challenger's dot lands.\n` +
  `export const STATE_XY: Record<string, { x: number; y: number }> = ${JSON.stringify(stateXY)};\n`;

writeFileSync(new URL('../apps/mobile/src/features/live/usMapData.ts', import.meta.url), out);
console.log(
  `Wrote usMapData.ts — ${statePaths.length} states, ${Object.keys(stateXY).length} centroids, ${out.length} bytes.`,
);
