/**
 * Regenerate apps/mobile/src/features/live/usMapData.ts — accurate continental-US state borders
 * (Albers-USA, AK/HI insets) plus demo-city coordinates projected through the SAME projection so the
 * presence dots land on the right cities.
 *
 * Usage (from repo root):
 *   npm i --no-save d3-geo topojson-client
 *   node scripts/genUsMap.mjs
 *
 * Source data: us-atlas states-10m (US Census cartographic boundaries, public domain).
 */
import { writeFileSync } from 'node:fs';
import * as topojson from 'topojson-client';
import { geoAlbersUsa, geoPath } from 'd3-geo';

const TOPO_URL = 'https://cdn.jsdelivr.net/npm/us-atlas@3/states-10m.json';
const W = 960;
const H = 600;

const topo = await fetch(TOPO_URL).then((r) => r.json());
const states = topojson.feature(topo, topo.objects.states);

const proj = geoAlbersUsa().fitSize([W, H], states);
const path = geoPath(proj);
const roundPath = (d) => (d ? d.replace(/-?\d+\.?\d*/g, (n) => Math.round(parseFloat(n))) : '');
const statePaths = states.features.map((f) => roundPath(path(f))).filter(Boolean);

// Demo members → real [lon, lat]. Add cities here as the seed grows.
const cities = {
  p1: [-118.12, 34.58], // Palmdale
  p2: [-97.74, 30.27], // Austin
  p3: [-104.99, 39.74], // Denver
  p4: [-122.68, 45.52], // Portland
  p5: [-87.63, 41.88], // Chicago
  p6: [-80.19, 25.76], // Miami
  p7: [-71.06, 42.36], // Boston
  p8: [-122.33, 47.61], // Seattle
  p9: [-86.78, 36.16], // Nashville
  p10: [-84.39, 33.75], // Atlanta
  p11: [-117.16, 32.72], // San Diego
  p12: [-74.0, 40.71], // New York
};
const cityXY = {};
for (const [id, lnglat] of Object.entries(cities)) {
  const p = proj(lnglat);
  if (p)
    cityXY[id] = { x: Math.round((p[0] / W) * 1e4) / 1e4, y: Math.round((p[1] / H) * 1e4) / 1e4 };
}

const out =
  `// AUTO-GENERATED by scripts/genUsMap.mjs (d3-geo geoAlbersUsa over us-atlas states-10m). Do not edit.\n` +
  `// Accurate continental-US state borders (AK/HI as insets), projected to a ${W}×${H} viewBox.\n` +
  `export const US_VIEWBOX = '0 0 ${W} ${H}';\n` +
  `export const US_STATE_PATHS: readonly string[] = ${JSON.stringify(statePaths)};\n` +
  `export const CITY_XY: Record<string, { x: number; y: number }> = ${JSON.stringify(cityXY)};\n`;

writeFileSync(new URL('../apps/mobile/src/features/live/usMapData.ts', import.meta.url), out);
console.log(`Wrote usMapData.ts — ${statePaths.length} states, ${out.length} bytes.`);
